version: "3.8"
services: 
    catalogdb:
        container_name: : catalogcontainerdb
        restart: always
        ports: 
            - "27017:27017"
        volumes: 
            - catalogdb_volume:/data/db
    basketdb:
        container_name: : basketcontainerdb
        restart: always
        ports: 
            - "6379:6379"
    discountdb:
        container_name: : discountcontainerdb
        restart: always
        ports: 
            - "5432:5432"
        volumes: 
            - discount_volume:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=Password12*
            - POSTGRES_DB=discountdb
    identitydb:
        container_name: : identitydbcontainerdb
        restart: always
        ports: 
            - "1433:1433"
        volumes: 
            - identitydb_volume:/var/opt/mssql/data
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12*
    orderdb:
        container_name: : ordercontainerdb
        restart: always
        ports: 
            - "1444:1433"
        volumes: 
            - orderdb_volume:/var/opt/mssql/data
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12*
    rabbitmq:
        container_name: rabbitmqcontainer
        restart: always
        ports: 
             - "5672:5672"
             - "15672:15672"